### ISSUE TITLE
JSON parsing errors

### ISSUE THREAD

**Issue by SAI-sentinal-ai** [SKaplanOfficial/Raycast-PromptLab#14]
When I run the `summarise github trending` command, it pulls out the first entry but outputs this to the terminal. I am using OpenAI endpoint. 

```11:28:00.490 Failed to get JSON from model output
11:28:03.889 Failed to get JSON from model output
11:28:03.889 Warning: Cannot update a component (`CommandResponse`) while rendering a different component (`CommandResponse`). To locate the bad setState() call inside `CommandResponse`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at CommandResponse (/Users/hsai002/.config/raycast/extensions/promptlab/search-commands.js:16447:11)
    at Nr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:6:2490)
    at ray-navigation-stack
    at _o (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:6:2088)
    at Suspense
    at wr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:2543)
    at ray-root
    at ti (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:6:3000)```

**Comment by Ein-Tim** [comment]
I'm also getting errors from using PromptLab now @SKaplanOfficial:

```
16:39:31.238 
TypeError: Cannot read properties of undefined (reading 'startsWith')

discover-commands.tsx:21:96

---
18:     Promise.resolve(LocalStorage.allItems()).then((commandData) => {
19:       const commandDataFiltered = Object.values(commandData).filter(
20:         (cmd, index) =>
21:           Object.keys(commandData)[index] != "--defaults-installed" && !Object.keys(cmd)[index].startsWith("id-")
22:       );
23:       setMyCommands(commandDataFiltered.map((data) => JSON.parse(data)));
24:     });
---

    at Array.filter (<anonymous>)
discover-commands.js:17069:62
```

<img width="759" alt="Bildschirmfoto 2023-06-02 um 16 40 44" src="https://github.com/SKaplanOfficial/Raycast-PromptLab/assets/67682506/d7d30a2f-49f4-411c-a49c-af612beecc53">

Is this another issue @SAI-sentinal-ai? In this case, I won't high jack this issue and open a new one.
