### ISSUE TITLE
Model is not supported - Failed to fetch data

### ISSUE THREAD

**Issue by CyberDuck79** [SKaplanOfficial/Raycast-PromptLab#28]
#### Error:
```
Error: Model is not supported
    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)
    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)
    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)
    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)
    at process.processImmediate (node:internal/timers:478:21)
```
When I launch a command, the error appear at the bottom left.

The error do not prevent the command from working, but it is a little annoying.
I am using a local model hosted with Ollama. I have tried to configure the model using both extension settings and the model manager.
At this moment, I am not sure what the extension is trying to do, but my command works fine.

**Comment by SKaplanOfficial** [comment]
This seems to be because Raycast no longer supports text-davinci-003, but I need to look into why the extension is trying to use that model in this case. Will have an update ready soon with a fix.
